project:
  type: website
  output-dir: _site

website:
  title: "Stable Diffusion from the Foundations"
  description: "A deep dive into Stable Diffusion based on fast.ai lesson 9"
  
  navbar:
    title: "Stable Diffusion Tutorial"
    left:
      - href: index.qmd
        text: Home
      - href: lesson_9.ipynb
        text: Lesson 9

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: true
    code-copy: true
    fig-width: 8
    fig-height: 6
    css: |
      /* Custom styles for the tutorial */
      .jupyter-wrapper {
        margin: 1rem 0;
      }
      
      .cell-output-display {
        margin: 1rem 0;
      }
      
      /* Improve code block styling */
      pre {
        background-color: #f8f9fa;
        border: 1px solid #e9ecef;
        border-radius: 0.375rem;
        padding: 1rem;
      }
      
      /* Better figure styling */
      figure {
        text-align: center;
        margin: 2rem 0;
      }
      
      figcaption {
        font-style: italic;
        color: #6c757d;
        margin-top: 0.5rem;
      }
      
      /* Math equations */
      .katex {
        font-size: 1.1em;
      }

jupyter: python3

execute:
  freeze: auto
  cache: true